# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NaukriDemo' do
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NaukriDemo

  

  platform :ios, '9.0'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  target 'NaukriDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NaukriDemo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NaukriDemo-tvOS

  target 'NaukriDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
